#!/usr/bin/env python3
"""Dasha Compute fine-tune engine backend: `mlx` (Apple Silicon, MLX LM).

Implements the engine-backend interface documented in finetune_runner.py:

    ENGINE_ID = "mlx"
    generate_config(spec, ctx) -> {"command", "config_path", "config_text"}
    run(config, ctx) -> dict   # terminal result incl. "engine": "mlx"
    report_telemetry(coordinator, token, job_id, update) -> dict
    doctor() -> int

The backend NEVER executes client-supplied code, shell, or YAML. It only
ever runs one fixed command — `python -m mlx_lm lora -c <job.yaml>` — where
job.yaml is generated deterministically by generate_config() from the
validated spec. Requires mlx-lm 0.31.x and huggingface_hub.
"""

import json
import os
import re
import signal
import subprocess
import sys
import threading
import time

import finetune_runner as core

ENGINE_ID = "mlx"
MLX_LM_MIN_VERSION = (0, 31)

# Provider-side base-model allowlist (defense in depth; the server's MODELS +
# license gate is authoritative). QLoRA is automatic on these 4-bit bases.
BASE_MODELS = {
    "qwen3-1.7b": {"repo": "mlx-community/Qwen3-1.7B-4bit", "size_tier": "1b", "min_memory_gb": 4},
    "qwen3-4b": {"repo": "mlx-community/Qwen3-4B-4bit", "size_tier": "3b", "min_memory_gb": 6},
    "qwen3-8b": {"repo": "mlx-community/Qwen3-8B-4bit", "size_tier": "8b", "min_memory_gb": 10},
    "gemma3-4b": {"repo": "mlx-community/gemma-3-4b-it-4bit", "size_tier": "3b", "min_memory_gb": 6},
}

# Fixed fields the client cannot change (spec §"Deterministic config generation").
FIXED_YAML_FIELDS = {
    "train": True,
    "grad_checkpoint": True,
    "mask_prompt": True,
    "optimizer": "adamw",
    "steps_per_report": 10,
    "steps_per_eval": 100,
    "report_to": "coordinator",
}

# Deterministic key order for the emitted YAML.
YAML_KEY_ORDER = (
    "model", "train", "data", "fine_tune_type", "num_layers", "batch_size",
    "iters", "val_batches", "learning_rate", "max_seq_length", "seed",
    "grad_checkpoint", "mask_prompt", "optimizer", "steps_per_report",
    "steps_per_eval", "save_every", "adapter_path", "resume_adapter_file",
    "report_to",
)


def _yaml_scalar(value):
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    return json.dumps(str(value))  # JSON strings are valid YAML scalars


def spec_to_yaml(spec, *, base_repo, train_path, valid_path, adapter_path, resume_adapter_file=None):
    """Generate the mlx-lm job.yaml deterministically from a sanitized spec.

    The ONLY YAML this backend will ever execute. `spec` must already have
    passed core.sanitize_spec(); client-supplied YAML is never accepted.
    """
    values = {
        "model": base_repo,
        "train": True,
        "data": os.path.dirname(train_path),
        "fine_tune_type": spec["finetune_type"],
        "num_layers": spec["lora_layers"],
        "batch_size": spec["batch_size"],
        "iters": spec["iters"],
        "val_batches": 25,
        "learning_rate": spec["learning_rate"],
        "max_seq_length": spec["max_seq_length"],
        "seed": spec["seed"],
        "grad_checkpoint": True,
        "mask_prompt": True,
        "optimizer": "adamw",
        "steps_per_report": 10,
        "steps_per_eval": 100,
        "save_every": spec["save_every"],
        "adapter_path": adapter_path,
        "resume_adapter_file": resume_adapter_file,
        "report_to": "coordinator",
    }
    lines = ["# generated by dasha-compute finetune_runner_mlx — do not hand-edit"]
    for key in YAML_KEY_ORDER:
        lines.append(f"{key}: {_yaml_scalar(values[key])}")
    lines.append(f"lora_rank: {_yaml_scalar(spec['lora_rank'])}")
    lines.append(f"train_file: {_yaml_scalar(os.path.basename(train_path))}")
    lines.append(f"valid_file: {_yaml_scalar(os.path.basename(valid_path))}")
    return "\n".join(lines) + "\n"


def build_train_command(config_path):
    """The one and only command this backend executes.

    config_path must point at a job.yaml produced by generate_config(); the
    path itself is derived from the job working directory, never from
    client input.
    """
    return [sys.executable, "-m", "mlx_lm", "lora", "-c", config_path]


def check_mlx_lm():
    try:
        import mlx_lm  # noqa: F401
        from importlib.metadata import version
        parts = tuple(int(p) for p in version("mlx-lm").split(".")[:2])
        return parts >= MLX_LM_MIN_VERSION, version("mlx-lm")
    except Exception as error:
        return False, str(error)


def ensure_base_model(repo):
    """Download/cache the allowlisted 4-bit base once. Returns local path."""
    from huggingface_hub import snapshot_download
    return snapshot_download(repo_id=repo, cache_dir=core.model_cache_dir())


def report_telemetry(coordinator, token, job_id, update):
    return core.report_progress(coordinator, token, job_id, update)


def generate_config(spec, ctx):
    """Build this backend's config from the sanitized spec; write job.yaml."""
    base = BASE_MODELS[spec["base_model"]]
    config_path = os.path.join(ctx.workdir, "job.yaml")
    config_text = spec_to_yaml(
        spec, base_repo=base["repo"], train_path=ctx.train_path,
        valid_path=ctx.valid_path, adapter_path=ctx.adapter_dir,
        resume_adapter_file=ctx.resume_dir,
    )
    with open(config_path, "w", encoding="utf-8") as handle:
        handle.write(config_text)
    return {"command": build_train_command(config_path),
            "config_path": config_path, "config_text": config_text,
            "spec": spec, "base_model": spec["base_model"]}


# ---------------------------------------------------------------------------
# Execution
# ---------------------------------------------------------------------------

def _rss_mb(pid):
    try:
        out = subprocess.run(["ps", "-o", "rss=", "-p", str(pid)],
                             capture_output=True, text=True, timeout=5).stdout.strip()
        return int(out) // 1024
    except Exception:
        return 0


class Watchdog:
    """Kills the trainer on wall-clock or memory overrun."""

    def __init__(self, process, max_wall_seconds, max_rss_mb):
        self.process = process
        self.deadline = time.monotonic() + max_wall_seconds
        self.max_rss_mb = max_rss_mb
        self.tripped = None
        self._stop = threading.Event()
        self._thread = threading.Thread(target=self._watch, daemon=True)

    def start(self):
        self._thread.start()

    def stop(self):
        self._stop.set()
        self._thread.join(5)

    def _watch(self):
        while not self._stop.wait(15):
            if self.process.poll() is not None:
                return
            if time.monotonic() > self.deadline:
                self.tripped = "wall_clock_exceeded"
                self.process.kill()
                return
            if self.max_rss_mb and _rss_mb(self.process.pid) > self.max_rss_mb:
                self.tripped = "memory_exceeded"
                self.process.kill()
                return


LOSS_LINE_RE = re.compile(r"[Ii]ter(?:ation)?\s+(\d+).*?[Ll]oss\s+([0-9.]+)")


def _parse_loss_line(line):
    match = LOSS_LINE_RE.search(line)
    if match:
        return int(match.group(1)), float(match.group(2))
    return None


def run(config, ctx):
    """Run the fixed trainer command; stream telemetry; return the result."""
    ok, mlx_version = check_mlx_lm()
    if not ok:
        raise RuntimeError(f"mlx-lm 0.31.x required: {mlx_version}")
    ensure_base_model(BASE_MODELS[config["base_model"]]["repo"])
    command = config["command"]
    process = subprocess.Popen(command, cwd=ctx.workdir, stdout=subprocess.PIPE,
                               stderr=subprocess.STDOUT, text=True, bufsize=1)
    watchdog = Watchdog(process, ctx.max_wall_seconds, ctx.max_rss_mb)
    watchdog.start()
    train_loss, iters_done = [], 0
    cancelled = threading.Event()

    def _on_signal(_signum, _frame):
        cancelled.set()
        try:
            process.terminate()
        except Exception:
            pass

    old_handlers = {s: signal.signal(s, _on_signal) for s in (signal.SIGINT, signal.SIGTERM)}
    try:
        for line in process.stdout:
            parsed = _parse_loss_line(line)
            if parsed:
                iters_done, loss = parsed
                train_loss.append(loss)
                update = {"iters_done": iters_done, "train_loss": loss}
                if ctx.progress_callback:
                    ctx.progress_callback(update)
                else:
                    report_telemetry(ctx.coordinator, ctx.token, ctx.job_id, update)
        process.wait()
    finally:
        for sig, handler in old_handlers.items():
            signal.signal(sig, handler)
        watchdog.stop()

    base_result = {"job_id": ctx.job_id, "engine": ENGINE_ID, "iters_done": iters_done,
                   "spec_hash": core.spec_hash(config["spec"])}
    if watchdog.tripped == "memory_exceeded":
        raise RuntimeError("trainer killed: memory cap exceeded")
    if watchdog.tripped == "wall_clock_exceeded" or cancelled.is_set():
        checkpoint_ref = None
        try:
            checkpoint_ref = core.upload_adapter_dir(ctx.coordinator, ctx.token, ctx.job_id, ctx.adapter_dir)
        except Exception:
            pass
        return {**base_result, "status": "preempted", "checkpoint_ref": checkpoint_ref}
    if process.returncode != 0:
        return {**base_result, "status": "failed",
                "error": f"mlx_lm exited with code {process.returncode}"}
    adapter_ref = core.upload_adapter_dir(ctx.coordinator, ctx.token, ctx.job_id, ctx.adapter_dir)
    return {**base_result, "status": "complete", "train_loss": train_loss,
            "adapter_ref": adapter_ref}


def doctor():
    failures = 0
    ok, detail = check_mlx_lm()
    print(f"mlx       {'ok · ' + detail if ok else 'failed · ' + detail}")
    failures += 0 if ok else 1
    print(f"mlx       bases: {', '.join(BASE_MODELS)}")
    return failures
